### PR TITLE
Use PropTypes

### LINKED ISSUE #22: Add prop-types to all components that take props
https://github.com/facebook/prop-types

remember to use `yarn add`, not `npm install`

### PR DESCRIPTION
**Pull request by GyozaGuy**
Implements basic PropTypes on all components. Also fixes some ESLint issues, ESLint is now 100% happy! :100: Definitely make suggestions if you see anything you think needs to be adjusted/tweaked/changed in any of the configs.

NOTE: I was originally going to do PropTypes using validator functions like so:
```js
MyComponent.propTypes = {
  numbers: PropTypes.arrayOf(PropTypes.number)
};
```
But it turns out after React 16, this has been discontinued: https://www.npmjs.com/package/prop-types#difference-from-reactproptypes--dont-call-validator-functions

This is news to me, so I'll have to understand this a bit better. For now, the PropTypes are just using the basic types (e.g. `PropTypes.array`, `PropTypes.string`, etc...).

### CODE REVIEW

**Comment by dcenatiempo** [comment]
you need to install the prop-types package: https://www.npmjs.com/package/prop-types to use `PropTypes.bool`, etc

**Comment by GyozaGuy** [comment]
> you just need to install the prop-types package: https://www.npmjs.com/package/prop-types

Turns out it was already installed, so I didn't need to do anything: https://github.com/House-of-Faith/RN-Chinese-Bible/pull/23/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L24

**Comment by GyozaGuy** [comment]
> you need to install the prop-types package: https://www.npmjs.com/package/prop-types to use `PropTypes.bool`, etc

`PropTypes.bool` and all of the other basic types work just fine, it's the validator functions that don't (e.g. `PropTypes.arrayOf()`, `PropTypes.shape()`, `PropTypes.oneOf()`, etc...).

**Comment by dcenatiempo** [comment]
Gotcha, sorry, I jumped the gun on the comment.

**Comment by dcenatiempo** [comment]
I just pulled down the branch and added eddited Chapter.js as follows:
```
Chapter.propTypes = {
  verses: PropTypes.arrayOf(PropTypes.string).isRequired,
};
```

and it works fine for me...

From what I understand, prop-types used to be included in react, but now its been extracted to its own package. I'm pretty sure the validator functions will work fine with the `prop-types` package.

I believe that article referenced above is an old package referring to older version of react with the built in `React.PropTypes`, not the stand alone `prop-types`

So you should be able to add in all the validator functions we need...

**Comment by GyozaGuy** [comment]
> I just pulled down the branch and added eddited Chapter.js as follows:
> 
> ```
> Chapter.propTypes = {
>   verses: PropTypes.arrayOf(PropTypes.string).isRequired,
> };
> ```
> 
> and it works fine for me...

Huh that's funny... I just tried it as well and it's working for me now too. :thinking: I had been getting warnings related to the link posted in the PR description, but after that I did end up completing removing `node_modules` and re-installing because I think I had some dependency issues, and I guess that fixed whatever it was. :man_shrugging: Awesome, I'll make a few more updates then!

**Pull request merged**
